name: Coding Standards

on:
  pull_request:
    branches:
      - 1.x
  push:
    branches:
      - 1.x

jobs:
  php-cs-fixer:
    name: PHP CS Fixer (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php-version:
          - '8.2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: cs2pr

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: '--working-dir=tools/php-cs-fixer'

      - name: Run PHP CS Fixer
        run: 'tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr'
