name: "Continuous Integration"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }})
    runs-on: ubuntu-20.04
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

    strategy:
      matrix:
        php-version:
          - '8.0'
          - '8.1'
        symfony-version:
          - '5.3.*'
          - '6.0.x@dev'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: zip
          coverage: pcov

      - name: Install Symfony Flex
        run: composer global require --no-progress --no-scripts --no-plugins symfony/flex

      - name: Set composer minimum stability
        run: composer config minimum-stability dev
        if: matrix.symfony-version == '6.0.x@dev'

      - name: Remove not compatible vendors
        run: composer remove --no-update --dev friendsofphp/php-cs-fixer
        if: matrix.symfony-version == '6.0.x@dev'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: highest
          composer-options: '--prefer-stable'

      - name: Setup Git
        run: |
          git config --global init.defaultBranch master
          git config --global user.email git-wrapper@leapt.io
          git config --global user.name "Leapt Git Wrapper"

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.php-version == '8.0' && matrix.symfony-version == '5.3.*'
