name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }})
    runs-on: ubuntu-22.04
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

    strategy:
      matrix:
        php-version:
          - '8.1'
          - '8.2'
        symfony-version:
          - '5.4.*'
          - '6.3.*'
          - '6.4.x-dev'
        include:
          - php-version: '8.0'
            symfony-version: '5.4.*'
          - php-version: '8.2'
            symfony-version: '7.0.x-dev'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: zip
          coverage: pcov

      - name: Install Symfony Flex
        run: |
          composer config --global --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Setup Git
        run: |
          git config --global init.defaultBranch main
          git config --global user.email git-wrapper@leapt.dev
          git config --global user.name "Leapt Git Wrapper"

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.php-version == '8.2' && matrix.symfony-version == '6.3.*'
