name: "Continuous Integration"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  continuous-integration:
    name: Continuous Integration - PHP ${{ matrix.php-version }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version:
          - '8.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: zip
          coverage: pcov
          tools: cs2pr

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: highest
          composer-options: '--prefer-stable'

      - name: Setup Git
        run: |
          git config --global init.defaultBranch master
          git config --global user.email git-wrapper@leapt.io
          git config --global user.name "Leapt Git Wrapper"

      - name: Run php-cs-fixer
        run: 'vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr'

      - name: Run phpstan
        run: 'vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr'

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
